python:
  - 3.5
  - 3.6
language: python
cache: pip
script: py.test
after_failure: cat test/diffengine.log
notifications:
  slack:
    rooms:
      secure: dqjEH4QDMP3oKux8Q7HY1uy6MkiY+Rz+t9BlCfxgTAK3PqMEeM5f+CbdOACWCV3pGWry1KIJsk7yCkC8gGIEIRg1uraOO6lil9KbdVsdYuMpE9H6e8HN/0WdSXhHPQ4gqozBGczXqWqRV2r55YUgGgm58thm3srTzcCLK9IRiVu4Xyx6HGUk50RbCJ6mW9rAopnFbsc2sgdw+A8eaaoWgHe+2BueJXpbTB5PJ0A1j4G0gyUJtxmpys4cODs2PlFiNOtPWMb804pKeqDufj5FwM+cgWMx3O+YDHjQMTWeDsdjHYz4nAkU0B+cakwE6MXbJ/WaPr9/Ho6pXEaQ5dXUj3j7ZUTT3vWhhR90iV3O/Cmp+U3PX0NpYs9M8RoFJh8CKTeeGZnFVUR5ujaYAKBNTYENzYWeCcm0e2oG+GOUJzWrcL5D4ooBattOEWUaVETEp3LVGhQOqArKse9HvKDNzGOYeaJSBTUPN3i/ODpcQbw1NhHNA2t58mC4N6gb0Om7SgNPcWtFz4sVyIvcQYL29RFCw5zaeim5/yWO8FEkWnwJKiq7yaD1jGWtUo985CQkkS39TgYjxLtS8J4xhNfYk56Nk4s8c0pXW20HUQkeDgbpDKSbSOMFAaIG8LfWyQAPCvk46ULOimsZHsUpKr7vbY9bfYm06OfUWh5DNRWFsrw=
